"""version_

Revision ID: 838732ab6f1c
Revises: cbb9537580cb
Create Date: 2022-07-16 20:55:37.350764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838732ab6f1c'
down_revision = 'cbb9537580cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    # ### end Alembic commands ###
